//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingDomainModel
{
    using System;
    using DomainModelFramework;using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class User : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int UserID { get; set; }
        [Required]
        public string UserName { get; set; }
        public bool IsActive { get; set; }
        public bool IsVerified { get; set; }
                
        
        

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
